version: '3.8'

services:
  user_service:
    build:
      context: ./user
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "5001:5001"

  dummy_service:
    build:
      context: ./dummy
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "5002:5002"
    depends_on:
      - user_service  # DummyServiceがUserServiceに依存する

  optimize_service:
    build:
      context: ./optimize
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "5003:5003"
    depends_on:
      - user_service  # DummyServiceがUserServiceに依存する
      - dummy_service
  
