version: '3.8'

services:
  user_service:
    build:
      context: ./api/user
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRE_SECONDS=${JWT_EXPIRE_SECONDS}
    ports:
      - "5001:5001"

  dummy_service:
    build:
      context: ./api/dummy
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "5002:5002"
    depends_on:
      - user_service

  optimize_service:
    build:
      context: ./api/optimize
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "5003:5003"
    depends_on:
      - user_service
      - dummy_service
  
