version: '3.8'

services:
  user_service:
    build:
      context: ./user
    environment:
      - JWT_SECRET_KEY=your_shared_secret_key  # シークレットキーは各サービスで共有
    ports:
      - "5001:5001"

  dummy_service:
    build:
      context: ./dummy
    environment:
      - JWT_SECRET_KEY=your_shared_secret_key # シークレットキーは各サービスで共有
    ports:
      - "5002:5002"
    depends_on:
      - user_service  # DummyServiceがUserServiceに依存する
