version: '3.8'

services:

  streamlit:
    build:
      context: ./streamlit
    environment:
      - USER_URL=http://user_service:5001/user
      - DUMMY_URL=http://dummy_service:5002/dummy
      - OPTIMIZE_URL=http://optimize_service:5003/optimize
    ports:
      - "8501:8501"

  user_service:
    build:
      context: ./api/user
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRE_SECONDS=${JWT_EXPIRE_SECONDS}
    ports:
      - "5001:5001"

  dummy_service:
    build:
      context: ./api/dummy
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "5002:5002"
    depends_on:
      - user_service

  optimize_service:
    build:
      context: ./api/optimize
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DUMMY_URL=http://dummy_service:5002/dummy
    ports:
      - "5003:5003"
    depends_on:
      - user_service
      - dummy_service
  
