apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: docker.io/library/user-service:latest  # Dockerfileのビルドイメージ名
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        env:
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: secret-key
        - name: JWT_EXPIRE_SECONDS
          value: "300"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: user-service
